### ISSUE TITLE
Add "New" button to create a new recipe

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#11]
This could also open a dialogue (popup) with "Don't show me this again" option that guides through the workflow:
Create Hardware Instrument -> create Analysis Instrument -> create Code Panel -> optionally add variables

**Comment by linzuzeng** [comment]
I think we can implement this as "the better error message from the compiler".
Instead of showing "NO ACCUSATION DEVICE IS FOUND" or "CREATE AT LEAST A VIRTUAL INSTRUMENT"  or "CREATE A CODE PANEL", we show nice animation (or even youtube video) of how to create them. We can also put a  "Don't show me this again" which switches back to the normal error message.

If the users started with a empty recipe, the order of seeing the error message is exactly 

> Hardware Instrument -> create Analysis Instrument -> create Code Panel

The benefit of doing it in this way is that , if the user made a incomplete recipe, he could still see the part of the nice guide.

**Comment by linzuzeng** [comment]
fixed in RC 5.2
