### ISSUE TITLE
display blob diagram shortcuts

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#12]
there could be a "?" icon in the corner that also shows the "Transitions" and "Actions" from the "Create" menu (we can remove it from there, then)

**Comment by linzuzeng** [comment]
Actually, I am not sure if the "Transitions" and "Actions" should go into the "Create" menu.
Usually people would expect the documentation and functions to be displayed differently, but here we mix them in a same menu, because the menu has the name of "Create"

A "?" icon could be a solution, but it could also hide the  "Transitions" and "Actions" forever.

**Comment by linzuzeng** [comment]
fixed in RC 5.1
