### ISSUE TITLE
display variables in code panel and instrument designer

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#19]
i think they would like this like in matlab / spyder. But it could of course also look pretty :)

**Comment by linzuzeng** [comment]
This must be a lovely feature, but also hard.

At the ETA Back-end, thanks to the check-pointing support since ETA RC4.x, we can now access all the contexts. Therefore this feature is possible to implement.
At the GUI side, it is easy to display the new thingy, INTEGER(). But it should be very ugly if we dump the array as string.

Also, do you also want it to be updated in real-time when the analysis is running?

**Comment by Cyberfly100** [comment]
what I meant is the variables from the home screen. variables as in not instument designer, code panel or hardware. Like binsize and the filename...

**Comment by linzuzeng** [comment]
Aha. Then it is easy.

Maybe we should call it "parameter" instead of "variable" to reduce the confusion.

**Comment by linzuzeng** [comment]
I think we could keep the home screen open, while editing on instrument designer, or code panel.
I made a new version rc5.1 for trying this. Looking forward to your opinion about it.
